# Generated by Django 4.1 on 2023-02-19 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('course_code', models.IntegerField(help_text='Indicates an invitation to the course using a code.', unique=True, verbose_name='code')),
                ('image', models.ImageField(upload_to='course/image/', verbose_name='image')),
                ('is_premium', models.BooleanField(default=False, help_text='Indicates a premium user who has access to premium features.', verbose_name='premium')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates a user who has an active account.', verbose_name='active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
