# Generated by Django 4.1 on 2023-02-24 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data created')),
                ('date_due', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='points')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates a task that has an active status.', verbose_name='active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
